### ISSUE TITLE
Failed to import Maritime Decision Aid Tools.tbx in ArcGIS Pro using Python

### ISSUE THREAD

**Issue by JudTown17** [Esri/solutions-geoprocessing-toolbox#403]
@mfunk , @jfrygeo :

When attempting to import the Maritime Decision Aid Tools.tbx using Python 3.4.3 for ArcGIS Pro (64-bit), I get the following error message:

**ERROR: 2016-03-21 09:44:28,894 PYTHON ERRORS:
Traceback info:
  File "C:\Data\Defense Solutions\solutions-geoprocessing-toolbox\utils\test\suitability_tests\VisibilityRangeAtSeaTestCase.py", line 82, in test_visibility_range_at_sea
    arcpy.ImportToolbox(toolboxPath, "mdat")

Error Info:
EOL while scanning string literal (Maritime Decision Aid Tools.tbx, line 218)**

Importing the corresponding toolbox (Maritime Decision Aid Tools_10.4.tbx) in Python 2.7 using ArcMap 10.4 works fine.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/129342386639048/129373043798134)

**Comment by jfrygeo** [comment]
The tool, "Visibility Range at Sea" uses a feature set to drop a location, it could be possible that the tool is expecting a location, and one is not passed. The tools will need to be rebuilt for ArcGIS Pro, where a feature class is needed to supply a position. @mfunk - Do we build ArcGIS Pro versions of tools in the ..\solutions-geoprocessing-toolbox\suitability\toolboxes\Maritime Decision Aid Tools.tbx? And the \Maritime Decision Aid Tools.tbx_10.4 version is for ArcMap?

**Comment by mfunk** [comment]
@jfrygeo Yes.
* **Maritime Decision Aid Tools.tbx** is for Pro 1.1+
* **Maritime Decision Aid Tools_10.4.tbx** is for Desktop 10.4+

Desktop toolboxes will increment with minor version updates.

**Comment by mfunk** [comment]
@JudTown17 can you verify this is fixed and close the issue?

**Comment by JudTown17** [comment]
@jfrygeo @mfunk This is still NOT fixed. I am still getting the above error message when attempting to import the Pro toolbox.

**Comment by jfrygeo** [comment]
I only fixed the ArcMap versions.

Sent from my iPhone

On May 2, 2016, at 5:31 PM, Judson Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jfrygeo&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=3RNPB9Ixv4O2d647APzRGt3wziEh_eX-5pijurXT1_E&s=qGzAX-OMMJm09oWqNXeW97krXtUOhEiS4RJabe4nbiU&e=> @mfunk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mfunk&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=3RNPB9Ixv4O2d647APzRGt3wziEh_eX-5pijurXT1_E&s=TcVi9FRHXPK9mq5J8jl8iVQnszJFj9i5esSHJ4WMgGU&e=> This is still NOT fixed. I am still getting the above error message when attempting to import the Pro toolbox.

-

**Comment by jfrygeo** [comment]
The tools may need to be rebuilt for pro.

Sent from my iPhone

On May 2, 2016, at 5:31 PM, Judson Hardy <notifications@github.com<mailto:notifications@github.com>> wrote:


@jfrygeo<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jfrygeo&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=3RNPB9Ixv4O2d647APzRGt3wziEh_eX-5pijurXT1_E&s=qGzAX-OMMJm09oWqNXeW97krXtUOhEiS4RJabe4nbiU&e=> @mfunk<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mfunk&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=LOFtvHGMxkJ_DWps2cZi-A&m=3RNPB9Ixv4O2d647APzRGt3wziEh_eX-5pijurXT1_E&s=TcVi9FRHXPK9mq5J8jl8iVQnszJFj9i5esSHJ4WMgGU&e=> This is still NOT fixed. I am still getting the above error message when attempting to import the Pro toolbox.

-

**Comment by mfunk** [comment]
@jfrygeo can you do the updates for Pro toolbox in the 'unittest' branch? Thanks!

**Comment by mfunk** [comment]
The tool/toolbox associated with this issue has been deprecated and is no longer actively supported. Earlier versions of this toolbox will still be available from previous [Releases](https://github.com/Esri/solutions-geoprocessing-toolbox/releases)
