### ISSUE TITLE
Fix failing GP toolbox unit tests - Solutions Geoprocessing Toolbox

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-geoprocessing-toolbox#630]
Script appears to hang on Sun Position Analysis unit tests.

http://JENKINS:8080/job/Solutions-GP%20Toolbox%20Unit%20tests%20-%20ArcMap/59/console

**Comment by csmoore** [comment]
@ACueva - I think this might actually be failing on DistanceToAsset tests because of a few issues I noted [here](https://github.com/Esri/solutions-geoprocessing-toolbox/pull/626#issuecomment-332921974) - I can confirm if you can provide access to that local machine for a quick test.

**Comment by csmoore** [comment]
Hang problem resolved with #633 - but there are 2 other errors/failures that are known issues with the space in the folder name (See: #571) - the folder name will need renamed to fully resolve.


```
RESULTS =================================================
Number of tests run: 27
Number succeeded: 25
Number of errors: 1
Number of failures: 1
Number of tests skipped: 0
Percent passing: 0.0
=========================================================

ERRORS ==================================================
test_create_geonames_gazetteer (geonames_tests.GeoNamesTestCase.GeoNamesTestCase)
Traceback (most recent call last):
  File "C:\jenkins\workspace\Solutions-GP Toolbox Unit tests - ArcMap\utils\test\geonames_tests\GeoNamesTestCase.py", li
ne 114, in test_create_geonames_gazetteer
    arcpy.CreateGeonamesGazetteerLocator_defensegeonames(locatorFeatureClass, locator)
  File "C:\jenkins\workspace\Solutions-GP Toolbox Unit tests - ArcMap\geonames\Geonames Tools_arcmap.tbx", line 29, in C
reateGeonamesGazetteerLocator
       A D I _ A S C I I N
RuntimeError: Object: Error in executing tool
FAILURES ================================================
test_hot_spots_by_area (incident_analysis_tests.HotSpotsByAreaTestCase.HotSpotsByAreaTestCase)
Traceback (most recent call last):
  File "C:\jenkins\workspace\Solutions-GP Toolbox Unit tests - ArcMap\utils\test\incident_analysis_tests\HotSpotsByAreaT
estCase.py", line 131, in test_hot_spots_by_area
    self.assertTrue(arcpy.Exists(outputFeatureClass))
AssertionError: False is not true
END OF TEST =========================================
```

**Comment by csmoore** [comment]
Removing the space from the path resolves the test errors above, but on **10.3.1** still leaves one remaining known issue noted in #388 (python crashes on exit with matplotlib error):

```
matplotlib\_pylab_helpers.py", line 84, in destroy_all for manager in Gcf.figs.values() AttributeError: 'NoneType' object has no attribute 'figs'
```

This is resolved at 10.4

**Comment by ACueva** [comment]
Verified.  Still crashing at end of test at 10.3.1.  Once Jenkins nodes are configured we can test at different versions.
